version: '3'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://user:password@db:27017/express-sample
    volumes:
      - .:/usr